project_id = "vsvhkkalfziuyttwityc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "https://www.foodvrse.com"
additional_redirect_urls = [
  "https://www.foodvrse.com/**",
  "https://www.foodvrse.com/oauth-callback"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.external.google]
enabled = true
client_id = "707536400304-6ogfei7hql85l4csjch467922du99hur.apps.googleusercontent.com"
secret = ""
redirect_uri = "https://www.foodvrse.com/oauth-callback"

[edge_runtime]
enabled = true

[analytics]
enabled = false
port = 54327

[functions.weekly-challenge-reset]
verify_jwt = false