project_id = "vsvhkkalfziuyttwityc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://7ed32c21-6ce4-4ba4-b153-74514b0212e7.lovableproject.com/**", "https://foodvrse.lovable.app/**", "https://id-preview--7ed32c21-6ce4-4ba4-b153-74514b0212e7.lovable.app/**", "https://preview--foodvrse.lovable.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = "http://localhost:8080/oauth-callback"

[edge_runtime]
enabled = true

[analytics]
enabled = false
port = 54327



[functions.weekly-challenge-reset]
verify_jwt = false