name: Supabase Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'
      - 'supabase/seed.sql'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-linux-amd64 -o supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin/
          supabase --version

      - name: Deploy to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "$SUPABASE_ACCESS_TOKEN" | supabase login
          supabase db push --project-ref vsvhkkalfziuyttwityc
          echo "✅ Supabase deployment completed!"
